apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name:
          image:<whule>/flask-app:v1
          ports: 5000
            - containerPort:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

---

apiVersion: v1
kind: Service
metadata:
  name:
spec: 
  selector:
    app: flask-app
  ports:
    - protocol: Tcp
      port: 80
      targetPort: 5000
  type: clusterIP
